name: Deploy to Amazon ECR

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 460195068877.dkr.ecr.us-east-2.amazonaws.com/atenea-frontend:latest

      - name: Log out from Amazon ECR
        run: docker logout 460195068877.dkr.ecr.us-east-2.amazonaws.com
